"""Add activity to PlannerEntry

Revision ID: 075f374041d7
Revises: 83800ea8e394
Create Date: 2026-01-05 23:27:29.120493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075f374041d7'
down_revision = '83800ea8e394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planner_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planner_entries', schema=None) as batch_op:
        batch_op.drop_column('activity')

    # ### end Alembic commands ###
