"""Added AI score and feedback to Submission

Revision ID: ea619669b80e
Revises: 075f374041d7
Create Date: 2026-01-06 20:18:27.245645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea619669b80e'
down_revision = '075f374041d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_submissions', schema=None) as batch_op:
        batch_op.drop_column('ai_feedback')
        batch_op.drop_column('ai_score')

    # ### end Alembic commands ###
